import 'package:bd_stock_trend/common/model/time_series.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'company_details.freezed.dart';

@freezed
class CompanyDetails with _$CompanyDetails {
  const factory CompanyDetails({
    required ScripDetailsInfo info,
    required List<TimeSeries> last30Days,
    required List<TimeSeries> next30Days,
  }) = _CompanyDetails;
}


@freezed
class ScripDetailsInfo with _$ScripDetailsInfo {
  const factory ScripDetailsInfo({
    required String scrip,
    required String fullName,
    required double lastTrade,
    required double volume,
    required double closePrice,
    required double week1Close,
    required double week52Close,
    required String week52Range,
    required double openPrice,
    required double ycp,
    required double marketCap,
    required double daysValue,
    required String lastUpdate,
    required String change,
    required double totalTrade,
    required double authorizedCap,
    required double paidUpCap,
    required double totalSecurities,
    required String lastAGMHeld,
    required double reserveSurplus,
    required int listingYear,
    required String marketCategory,
    required String electronic,
    required String shareHoldingPercentage,
    required double sponsorDirector,
    required double govt,
    required double institute,
    required double foreign,
    required double public,
    required String shareHoldingPercentage1,
    required double sponsorDirector1,
    required double govt1,
    required double institute1,
    required double foreign1,
    required double public1,
    required String shareHoldingPercentage2,
    required double sponsorDirector2,
    required double govt2,
    required double institute2,
    required double foreign2,
    required double public2,
    required String presentOs,
    required String presentLs,
    required int shortLoan,
    required int longLoan,
    required String? latestDividendStatus,
    required String address,
    required String contact,
    required String email,
    required String web,
    required String? rating,
    required double changePer,
    required String dayRange,
    required double eps,
    required double auditedPE,
    required double unAuditedPE,
    required double q1Eps,
    required double q2Eps,
    required double q3Eps,
    required double q4Eps,
    required double nav,
    required double navPrice,
    required double freefloat,
    required String ye,
    required double dividendYield,
    required String news1stdate,
    required String news1sttitle,
    required String news1stbody,
    required String news2stdate,
    required String news2sttitle,
    required String news2stbody,
    required String news3stdate,
    required String news3sttitle,
    required String news3stbody,
    required String news4stdate,
    required String news4sttitle,
    required String news4stbody,
    required String news5stdate,
    required String news5sttitle,
    required String news5stbody,
    required String ma10,
    required String ma20,
    required String ma50,
    required String ma100,
    required String ma200,
    required String maAVG,
    required String ema10,
    required String ema20,
    required String ema50,
    required String ema100,
    required String ema200,
    required String emaAVG,
    required String stockBeta,
  }) = _ScripDetailsInfo;
}